# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-21 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(default='/home/karangu/Desktop/Instagram\\ clone/media', upload_to='images/'),
        ),
    ]
