# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-23 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_comments_image_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='liked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='image',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
